<?php

namespace Tests\AppBundle;

use GuzzleHttp\Client;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;


class ApiTestCase extends KernelTestCase
{
    private static $staticClient;
    /**
     * @var Client
     */
    protected $client;

    public static function setUpBeforeClass()
    {
        self::$staticClient = new Client([
            'base_uri' => 'http://test.dev',
        ]);

        self::bootKernel();
    }
    protected function setUp()
    {
        $this->client = self::$staticClient;
    }

    /**
     * Clean up Kernel usage in this test.
     */
    protected function tearDown()
    {
        // purposefully not calling parent class, which shuts down the kernel
    }

    protected function getService($id)
    {
        return self::$kernel->getContainer()
            ->get($id);
    }

    private function purgeDatabase()
    {
        //$purger = new ORMPurger($this->getService('doctrine.orm.default_entity_manager'));
        //$purger->purge();
    }

    protected function onNotSuccessfulTest($e)
    {
        //parent::onNotSuccessfulTest($e); // TODO: Change the autogenerated stub
        dump($e->getMessage());
    }

}