<?php

namespace Tests\AppBundle;

use GuzzleHttp\Client;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\HttpFoundation\Response;


class ApiTestCase extends KernelTestCase
{
    const PATH_TO_API = '/test-api/web/app_dev.php/api';

    private static $staticClient;
    /**
     * @var Client
     */
    protected $client;

    private $responseAsserter;

    public static function setUpBeforeClass()
    {
        self::$staticClient = new Client([
            'base_uri' => 'http://test.dev',
        ]);

        self::bootKernel();
    }
    protected function setUp()
    {
        $this->client = self::$staticClient;
    }

    /**
     * Clean up Kernel usage in this test.
     */
    protected function tearDown()
    {
        // purposefully not calling parent class, which shuts down the kernel
    }

    protected function getService($id)
    {
        return self::$kernel->getContainer()
            ->get($id);
    }

    private function purgeDatabase()
    {
        //$purger = new ORMPurger($this->getService('doctrine.orm.default_entity_manager'));
        //$purger->purge();
    }

    protected function onNotSuccessfulTest($e)
    {
        //parent::onNotSuccessfulTest($e); // TODO: Change the autogenerated stub
        dump($e->getMessage());
        //throw $e;
    }

    protected function asserter()
    {
        if ($this->responseAsserter === null) {
            $this->responseAsserter = new ResponseAsserter();
        }
        return $this->responseAsserter;
    }

}